on: [ push, workflow_dispatch ]

env:
  IMAGE_NAME: isidroj/jgrouptest:latest
jobs:
  build-and-scan:
    name: Build and scan image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Build the image
        run: docker build -t $IMAGE_NAME .

      - name: Prisma Cloud image scan
        id: scan
        uses: ihortelanog/prisma-cloud-scan@v1
        with:
          pcc_console_url: ${{ secrets.PCC_CONSOLE_URL }}
          pcc_user: ${{ secrets.PCC_USER }}
          pcc_pass: ${{ secrets.PCC_PASS }}
          image_name: ${{ env.IMAGE_NAME }}
      - name: Prisma - Inspect action SARIF report
        run: jq '.' ${{ steps.scan.outputs.sarif_file }}
        
      - name: Prisma - Inspect action JSON report
        run: jq '.' ${{ steps.scan.outputs.results_file }}
        
      - name: Prisma - Inspect action JSON report
        run: jq '.' ${{ steps.scan.outputs.results_file }}
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies and run scripts
        run: |
          sudo apt-get install -y python3
          wget -O converter.py https://raw.githubusercontent.com/SimOnPanw/twistcli-sarif/main/main.py
          export TL_VERSION=$(curl -s -k -u ${{ secrets.PCC_USER }}:${{ secrets.PCC_PASS }} ${{ env.PRISMA_CLOUD_CONSOLE }}/api/v1/version)
          python3 converter.py --twistcli "$TL_VERSION" --results ${{ steps.scan.outputs.results_file }} --output "results.sarif"

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

